-- FR-UC-08: bitácora de avisos de SLA ya emitidos.
--
-- El barrido corre cada pocos minutos sobre las mismas solicitudes; sin esta tabla, una solicitud
-- vencida generaría un aviso en cada pasada. La clave única por (solicitud, tipo) hace que cada
-- aviso se emita exactamente una vez, y lo hace en la base y no en memoria, para que reiniciar el
-- backend no vuelva a notificar lo ya notificado.
--
-- Renumerada desde la V8 de la rama de contratos. Se usa GENERATED BY DEFAULT AS IDENTITY en lugar
-- de BIGSERIAL porque es la forma estándar y H2 la entiende igual que PostgreSQL.

CREATE TABLE sla_events_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL REFERENCES repair_requests(id) ON DELETE CASCADE,
    event_type VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_sla_event_type CHECK (event_type IN ('SLA_WARNING', 'SLA_BREACH')),
    CONSTRAINT uq_sla_events_request_type UNIQUE (request_id, event_type)
);

CREATE INDEX ix_sla_events_request ON sla_events_log (request_id);
